version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      # - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > sh.rustup.rs
      # - chmod +x sh.rustup.rs && ./sh.rustup.rs -y
      # - mkdir -p /mdbook/bin
      # - curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=/mdbook/bin
      # - /root/.cargo/bin/cargo install mdbook-indexing
    finally:
      - echo mdbook installed correctly
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo pre_build finished
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      # - export PATH=/root/.cargo/bin:$PATH
      - /mdbook/bin/mdbook build
    finally:
      - echo build finished
  post_build:
    commands:
      - echo Entered the post_build phase...
      - ls -lah book
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: book
  discard-paths: no
