site_name: Ricette
repo_url: https://github.com/antonio-fasolato/ricette
# theme:
#   name: terminal
#   palette: Dark
#theme: 'windmill'

# D&D!
#theme: 'torillic'
theme:
  name: material
  favicon: img/favicon.png
  features:
    - header.autohide

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags

nav:
  - Home: index.md
  - Antipasti: antipasti/index.md
  - Primi: primi/index.md
  - Secondi: secondi/index.md
  - Da provare: da-provare/index.md
  - "": ""
  - Tags: tags.md
