site_name: Ricette
repo_url: https://github.com/antonio-fasolato/ricette
# theme:
#   name: terminal
#   palette: Dark
#theme: 'windmill'

# D&D!
#theme: 'torillic'

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - Antipasti: antipasti/index.md
  - Primi: primi/index.md
  - Secondi: secondi/index.md
  - Da provare: da-provare/index.md
